# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TVHChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('number', models.IntegerField(default=0)),
                ('user_icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('auto_epg_channel', models.BooleanField(default=True)),
                ('dvr_pre', models.IntegerField(default=0)),
                ('dvr_post', models.IntegerField(default=0)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TVHChannelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='TVHEPGSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='TVHMux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_index', models.IntegerField(default=0)),
                ('internal', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_has_title', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TVHNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('networkname', models.CharField(max_length=255)),
                ('orbital_pos', models.CharField(max_length=10)),
                ('nid', models.IntegerField(default=0)),
                ('autodiscovery', models.BooleanField(default=True)),
                ('skipinitscan', models.BooleanField(default=True)),
                ('idlescan', models.BooleanField(default=False)),
                ('sid_chnum', models.BooleanField(default=False)),
                ('satip_source', models.IntegerField(default=0)),
                ('charset', models.CharField(blank=True, max_length=255, null=True)),
                ('localtime', models.BooleanField(default=False)),
                ('networkclass', models.CharField(choices=[(b'dvb_network_dvbs', b'DVB Sat')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TVHRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('startdt', models.DateTimeField()),
                ('enddt', models.DateTimeField()),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('schedstate', models.CharField(max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvhm.TVHChannel')),
            ],
        ),
        migrations.CreateModel(
            name='TVHRecordingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvhm.TVHRecording')),
            ],
        ),
        migrations.CreateModel(
            name='TVHServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=9981)),
                ('htsp', models.PositiveIntegerField(default=9982)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TVHService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('mux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvhm.TVHMux')),
            ],
        ),
        migrations.AddField(
            model_name='tvhrecording',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvhm.TVHServer'),
        ),
        migrations.AddField(
            model_name='tvhnetwork',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvhm.TVHServer'),
        ),
        migrations.AddField(
            model_name='tvhchannel',
            name='channeltags',
            field=models.ManyToManyField(blank=True, to='tvhm.TVHChannelTag'),
        ),
        migrations.AddField(
            model_name='tvhchannel',
            name='epg_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvhm.TVHEPGSource'),
        ),
        migrations.AddField(
            model_name='tvhchannel',
            name='services',
            field=models.ManyToManyField(to='tvhm.TVHService'),
        ),
    ]
